/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;

/**
 *
 * @author nico
 */
public class ViewFormInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewFormInscripcion
     */
    public ViewFormInscripcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormInscripcion = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnInscribir = new javax.swing.JButton();
        lblElijMateria = new javax.swing.JLabel();
        lblElijAlumno = new javax.swing.JLabel();
        comBoxMateria = new javax.swing.JComboBox<>();
        comBoxMAlumno = new javax.swing.JComboBox<>();

        lblFormInscripcion.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        lblFormInscripcion.setForeground(new java.awt.Color(0, 0, 255));
        lblFormInscripcion.setText("Formulario de Inscripción");

        btnSalir.setBackground(new java.awt.Color(250, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setAutoscrolls(true);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnInscribir.setText("Inscribir");

        lblElijMateria.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        lblElijMateria.setForeground(new java.awt.Color(0, 0, 255));
        lblElijMateria.setText("ELIJA UNA MATERIA:");

        lblElijAlumno.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        lblElijAlumno.setForeground(new java.awt.Color(0, 0, 255));
        lblElijAlumno.setText("ELIJA UN ALUMNO:");

        comBoxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxMateriaActionPerformed(evt);
            }
        });

        comBoxMAlumno.setModel(comBoxMAlumno.getModel());
        comBoxMAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxMAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnInscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lblFormInscripcion)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblElijMateria)
                            .addComponent(lblElijAlumno))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comBoxMAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comBoxMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(80, 80, 80)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormInscripcion)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElijMateria)
                    .addComponent(comBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElijAlumno)
                    .addComponent(comBoxMAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxMateriaActionPerformed
        // TODO add your handling code here:
        
        
         
         
    }//GEN-LAST:event_comBoxMateriaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void comBoxMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxMAlumnoActionPerformed
        // TODO add your handling code here:
        
        comBoxMAlumno.addItem("eaa");
      
        ComboBoxModel<String> cbm = null;
        cbm.setSelectedItem(ViewMenuPpal.alum);
       
        comBoxMAlumno.setModel(cbm);
        
    }//GEN-LAST:event_comBoxMAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comBoxMAlumno;
    private javax.swing.JComboBox<String> comBoxMateria;
    private javax.swing.JLabel lblElijAlumno;
    private javax.swing.JLabel lblElijMateria;
    private javax.swing.JLabel lblFormInscripcion;
    // End of variables declaration//GEN-END:variables
}
