/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import tp7_lab1_grupo01.Alumno;
import tp7_lab1_grupo01.Materia;

/**
 *
 * @author nico
 */
public class ViewMenuPpal extends javax.swing.JFrame {
    
   public static Alumno alum = new Alumno();
    public static Materia mat = new Materia();
    

    /**
     * Creates new form viewMenu
     */
    public ViewMenuPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFormularios = new javax.swing.JMenu();
        menuForMateria = new javax.swing.JMenuItem();
        menuForAlumno = new javax.swing.JMenuItem();
        menuForInscripcion = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuCerrarPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        menuFormularios.setText("Formularios");

        menuForMateria.setText("Formulario de Materias");
        menuForMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuForMateriaActionPerformed(evt);
            }
        });
        menuFormularios.add(menuForMateria);

        menuForAlumno.setText("Formulario de Alumnos");
        menuForAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuForAlumnoActionPerformed(evt);
            }
        });
        menuFormularios.add(menuForAlumno);

        menuForInscripcion.setText("Formulario de Inscripcion");
        menuForInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuForInscripcionActionPerformed(evt);
            }
        });
        menuFormularios.add(menuForInscripcion);

        jMenuBar1.add(menuFormularios);

        menuSalir.setText("Salir");

        menuCerrarPrograma.setText("Cerrar Programa");
        menuCerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarProgramaActionPerformed(evt);
            }
        });
        menuSalir.add(menuCerrarPrograma);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuForMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuForMateriaActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        ViewFormMaterias forMat = new ViewFormMaterias();
        forMat.setVisible(true);
        escritorio.add(forMat);
        escritorio.moveToFront(forMat);
    }//GEN-LAST:event_menuForMateriaActionPerformed

    private void menuForAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuForAlumnoActionPerformed
        // TODO add your handling code here:
        
         escritorio.removeAll();
        escritorio.repaint();
        ViewFormAlumno forAlum = new ViewFormAlumno();
        forAlum.setVisible(true);
        escritorio.add(forAlum);
        escritorio.moveToFront(forAlum);
    }//GEN-LAST:event_menuForAlumnoActionPerformed

    private void menuForInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuForInscripcionActionPerformed
        // TODO add your handling code here:
        
          escritorio.removeAll();
        escritorio.repaint();
        ViewFormInscripcion forInsc = new ViewFormInscripcion();
        forInsc.setVisible(true);
        escritorio.add(forInsc);
        escritorio.moveToFront(forInsc);
    }//GEN-LAST:event_menuForInscripcionActionPerformed

    private void menuCerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarProgramaActionPerformed
        // TODO add your handling code here:
        
     System.exit(0);
    }//GEN-LAST:event_menuCerrarProgramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCerrarPrograma;
    private javax.swing.JMenuItem menuForAlumno;
    private javax.swing.JMenuItem menuForInscripcion;
    private javax.swing.JMenuItem menuForMateria;
    private javax.swing.JMenu menuFormularios;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
